FROM ubuntu:focal

WORKDIR /tmp

RUN useradd -ms /usr/sbin/nologin bitcoin

COPY scripts/setup_tor.sh .
RUN chmod +x ./setup_tor.sh
RUN ./setup_tor.sh

COPY scripts/setup_btc_pi.sh .
RUN chmod +x ./setup_btc_pi.sh
RUN ./setup_btc_pi.sh